fix test again

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -36,12 +36,12 @@ jobs:
     
     - name: Test webpage
       run: |
-        curl localhost:8080
-        if [ $? -eq 0 ]
-          echo "Web page is running"
-        else
-          echo "Web page isn't running"
+        curl -sSf localhost:3000 >/dev/null
+        if [ $? -ne 0 ]; then
+          echo "Page not found."
           exit 1
+        else
+          echo "Page found."
         fi
     
     - name: Push to registry
